server: your.domain.net:443
auth: some_password
tls:
  sni: your.domain.net
#  insecure: false
#  pinSHA256: BA:88:45:17:A1...
#  ca: custom_ca.crt
bandwidth:
  up: 20 mbps
  down: 100 mbps

lazy: true

socks5:
  listen: 127.0.0.1:1080
http:
  listen: 127.0.0.1:7080

tcpTProxy:
  listen: :9898
udpTProxy:
  listen: :9898
