#!/system/bin/sh
# Override values from /data/adb/box/settings.ini.
#
# Warning about derived variables:
# - user.settings.ini is sourced near the END of settings.ini.
# - If you override base values, derived paths (e.g. `bin_path`, `clash_config`) are NOT recomputed.
# - Override derived paths too if needed.
#
# Examples:
# tproxy_port="1234"
# redir_port="5678"